name: cd
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install emacs
        uses: purcell/setup-emacs@master
        with:
          version: 26.3
      - name: Checkout
        uses: actions/checkout@v1
      - name: Smoke test
        run: |
          env HOME="${PWD}" emacs --fg-daemon --eval '(condition-case err (progn (load-file "./init.el") (kill-emacs)) (error (message "error: %s" err) (kill-emacs -1)))'
