name: cd
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install emacs
        uses: purcell/setup-emacs@master
        with:
          version: 26.3
      - name: Checkout
        uses: actions/checkout@v1
      - name: Smoke test
        run: |
          cd ..
          mv literally.el .emacs.d
          env HOME="${PWD}" emacs --fg-daemon --eval '(kill-emacs)'
